Update hadith API
oovaa/hasanah pull request #4
Opened 2024-12-03 12:28 UTC by baaki20

2024-12-07 08:17 UTC, oovaa requested changes
good job my friend but we need some work to improve it

2024-12-07 08:17 UTC, oovaa commented on .env
will vscode use your env file ?
check this online or ask the support team

2024-12-07 08:17 UTC, oovaa commented on hasanah/connect.js
have you checked if vscode supports .mjs files ?

sorry for asking to many questions but this extension is important for me and we are both learning new things

2024-12-07 08:17 UTC, oovaa commented on hasanah/hadith.mjs
is my previous function working well if the language is set to Arabic ?

we need to use the two apis

2024-12-07 08:17 UTC, oovaa commented on hasanah/hadith.mjs
you can create a separate English hadith file and import the ready function

2024-12-08 09:37 UTC, baaki20 commented on .env
I searched online and the answer was no. That we will need to configure the extension to access the variable stored in it

2024-12-08 09:42 UTC, baaki20 commented on hasanah/connect.js
So far I haven't encountered any problems but I'll try to change it back to .js.
The reason why the file was stored as .mjs was that, I was encountering some errors, the errors vanished after I changed the file extension to .mjs

2024-12-08 09:43 UTC, baaki20 commented on hasanah/hadith.mjs
> is my previous function working well if the language is set to Arabic ?
> 
> we need to use the two apis

Yes, it was working perfectly.

2024-12-08 10:47 UTC, closed without merging